filetype: unknown

detect:
    filename: ""

rules:
    # Mails
    - special: "[[:alnum:].%_+-]+@[[:alnum:].-]+\\.[[:alpha:]]{2,}"
    # URLs
    - identifier: "(https?|ftp|ssh)://\\S+\\.\\S+[^])>\\s,.]"

    - comment:
        start: "(^|\\s)#"
        end: "$"
        rules:
            - todo: "(TODO|XXX|FIXME):?"
